# Generated by Django 2.2.3 on 2021-11-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
