# Generated by Django 2.2.3 on 2021-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20211129_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dirreccion',
            field=models.CharField(max_length=50, verbose_name='La dirrección'),
        ),
    ]
